KomodoPlatform/komodo-defi-sdk-flutter

packages/komodo_wallet_build_transformer/lib/src/steps/fetch_defi_api_build_step.dart
Fixes the "npm not found" build step error when building for iOS through Xcode, and adds multiple lookup options for the npm path on Windows and Unix-based platforms.
=> fix(build-transformer): ios xcode errors

packages/komodo_defi_framework/lib/src/operations/kdf_operations_local_executable.dart, packages/komodo_defi_framework/lib/src/operations/kdf_operations_wasm.dart, playground/lib/kdf_operations/kdf_operations_server.dart, playground/lib/kdf_operations/kdf_operations_server_native.dart, playground/lib/kdf_operations/kdf_operations_server_stub.dart, playground/lib/kdf_operations/kdf_operations_server_web.dart, playground/lib/main.dart, playground/macos/Podfile.lock, playground/macos/Runner/Info.plist
Implement status polling similar to the approach used for `KdfOperationsLocalExecutable`. 
- Wait duration was reduced from 30 seconds to 15, since the WASM implementation does not have a process to watch for exit status codes.
One alternative could be to add a callback function to KDF for startup success/failure, similar to the log function callback. This would provide instant feedback in case of failure, similar to the process exit code watching done on native platforms.
=> fix(komodo-defi-framework): normalise kdf startup process between native and wasm

packages/komodo_defi_framework/.gitignore, packages/komodo_defi_framework/pubspec.yaml
explicitly exports the `coin_icons/png` assets folder in the `komodo_defi_framework` package so that the icons can be used by downstream packages, like `komodo-wallet`.
=> fix(komodo-defi-framework): export coin icons

.gitignore, packages/komodo_defi_framework/lib/src/operations/kdf_operations_native.dart, packages/komodo_defi_framework/lib/src/operations/kdf_operations_wasm.dart, packages/komodo_defi_framework/web/res/kdf_wrapper.dart
Only log pre-cast responses on wasm in debug mode. 
CI integration test log zip size:
- [before integration](https://github.com/KomodoPlatform/komodo-wallet-private/actions/runs/11437890363): 28.5 KB
- [after integration](https://github.com/KomodoPlatform/komodo-wallet-private/actions/runs/11801551026/attempts/1?pr=177): 954 KB (includes debug print statements added to the integration tests, which inflates it slightly)
=> fix(kdf_operations): reduce wasm log verbosity in release mode

packages/komodo_defi_framework/app_build/build_config.json, packages/komodo_defi_framework/lib/src/operations/kdf_operations_wasm.dart, packages/komodo_defi_framework/web/res/kdf_wrapper.dart, playground/lib/kdf_operations/kdf_operations_server_web.dart
- Migrate from `dart:js` and `dart:js_util` to `dart:js_interop`
- Fix type conversion of JS response objects
- Improve JS interop and error handling
The original goal was to fix uncaught async errors without a stacktrace, but that appears to be a non-critical bug related to coin activation - breakpoint steps into `activation_strategy_base.dart` (line 122 `yield* strategy.activate(asset, children)`)
=> fix(kdf-wasm-ops): response type conversion and migrate to js_interop

packages/komodo_defi_types/lib/types.dart
remove `legacy_coin_model.dart` from the types index, which was causing builds to fail
=> fix: defi types index

packages/komodo_defi_framework/app_build/build_config.json, packages/komodo_defi_framework/pubspec.yaml, packages/komodo_defi_local_auth/pubspec.yaml, packages/komodo_defi_sdk/example/pubspec.yaml, packages/komodo_defi_sdk/pubspec.yaml, packages/komodo_defi_types/lib/komodo_defi_types.dart, packages/komodo_wallet_cli/pubspec.lock, playground/macos/Flutter/GeneratedPluginRegistrant.swift, playground/pubspec.lock, playground/pubspec.yaml, playground/windows/flutter/generated_plugin_registrant.cc, playground/windows/flutter/generated_plugins.cmake
Removes the dependency override and fixes the flutter dependency errors
=> chore(deps): update flutter_secure_storage to v9.2.4

packages/komodo_defi_sdk/lib/src/assets/asset_manager.dart
Fixes a runtime error in KW (see in [2521](https://github.com/KomodoPlatform/komodo-wallet/pull/2521)) where the Wallet page fails to load due to legacy ticker index not being initialized
=> fix(asset-manager): asset ticker initialisation

packages/komodo_wallet_build_transformer/lib/src/steps/defi_api_build_step/artefact_downloader.dart, packages/komodo_wallet_build_transformer/lib/src/steps/defi_api_build_step/artefact_downloader_factory.dart, packages/komodo_wallet_build_transformer/lib/src/steps/defi_api_build_step/dev_builds_artefact_downloader.dart, packages/komodo_wallet_build_transformer/lib/src/steps/defi_api_build_step/github_artefact_downloader.dart, packages/komodo_wallet_build_transformer/lib/src/steps/defi_api_build_step/node_path.dart, packages/komodo_wallet_build_transformer/lib/src/steps/fetch_defi_api_build_step.dart, packages/komodo_wallet_build_transformer/lib/src/util/logging.dart
- Moved download logic out to separate files
- Reduced log stack trace verbosity by setting the stack trace printing threshold to `SEVERE` and higher
=> refactor(build_transformer): move api release download and extraction to separate files

packages/komodo_defi_sdk/lib/src/transaction_history/transaction_history_manager.dart, packages/komodo_defi_sdk/lib/src/transaction_history/transaction_history_strategies.dart
Re-enables non-HD transaction history support by adding `KomodoDefiLocalAuth` to `V2TransactionStrategy` through dependency injection via `TransactionHistoryStrategyFactory`.
=> fix(transaction-history): re-enable non-hd transaction history support

packages/komodo_defi_local_auth/lib/src/auth/auth_service.dart, packages/komodo_defi_local_auth/lib/src/auth/auth_service_auth_extension.dart, packages/komodo_defi_local_auth/lib/src/komodo_defi_local_auth.dart, packages/komodo_defi_sdk/lib/src/transaction_history/transaction_history_manager.dart, packages/komodo_defi_sdk/lib/src/transaction_history/transaction_storage.dart, packages/komodo_defi_types/lib/src/auth/auth_options.dart, packages/komodo_defi_types/lib/src/auth/kdf_user.dart, packages/komodo_defi_types/lib/src/transactions/asset_transaction_history_id.dart, packages/komodo_defi_types/lib/src/types.dart
- fix infinite loop in transaction stream retry logic
- refactor storage interface to use combination of wallet and asset as ID
- fix transaction storage error where new transactions streamed in are not available in the `_compareTransactions` function, resulting in transaction storage exceptions.
=> fix(transaction-storage): transaction streaming errors and hanging due to storage error

.gitignore, packages/komodo_defi_framework/ios/komodo_defi_framework.podspec, packages/komodo_defi_framework/macos/komodo_defi_framework.podspec.staticlib, packages/komodo_defi_framework/src/CMakeLists.txt, packages/komodo_wallet_build_transformer/lib/src/steps/fetch_defi_api_build_step.dart
Fixes Android build error by enforcing consistent filenames regardless of download source. All executables and libraries are now renamed from 'mm2' to 'kdf' with a `.replaceAll` operation on the filename.
=> build: rename libraries from 'mm2' to 'kdf'

packages/komodo_defi_framework/app_build/build_config.json
Update bundle checksums to match the KDF artefacts in 84f5c9235f2c90c07c600dd53ca13fd9d63052af (forgot to add it in #30)
=> chore(deps): update kdf checksums

packages/komodo_defi_framework/app_build/build_config.json
Update the KDF commit hash and checksums to the final release once available. 
KDF `dev` branch will be used, and this PR will remain in draft until then.
=> chore(deps): kdf 2.4.0 update

packages/komodo_defi_framework/app_build/build_config.json
Update to latest KDF `dev` branch commit: 0a22a7ed9441b5b9f2e2f05625678671af31b3d4
Builds might start failing if the pinned KDF commit is no longer available on the KDF dev builds site
=> chore(deps): kdf 2.4.0 update from `dev`

packages/komodo_defi_framework/lib/komodo_defi_framework.dart, packages/komodo_defi_framework/lib/src/config/kdf_logging_config.dart, packages/komodo_defi_framework/lib/src/operations/kdf_operations_native.dart, packages/komodo_defi_framework/lib/src/operations/kdf_operations_remote.dart, packages/komodo_defi_framework/lib/src/operations/kdf_operations_wasm.dart
Currently limited to the `komodo_defi_framework` package which is the source of the majority of log messages
=> refactor(komodo_defi_framework): add static, global log verbosity flag

packages/komodo_ui/lib/src/defi/withdraw/source_address_field.dart
For use in other places where the balance field is not desired, like the fiat form
=> feat(source-address-field): add show balance toggle

packages/komodo_defi_framework/app_build/build_config.json, packages/komodo_defi_framework/lib/src/operations/kdf_operations_native.dart, packages/komodo_defi_local_auth/lib/src/auth/auth_service_kdf_extension.dart, packages/komodo_defi_sdk/example/ios/Runner.xcodeproj/project.pbxproj, packages/komodo_defi_sdk/example/ios/Runner/Info.plist, packages/komodo_defi_sdk/example/web/kdf/res/kdf_wrapper.dart, packages/komodo_defi_types/lib/src/utils/security_utils.dart
Removes `findExceptionsInLog` from the `_restartKdf` function, which is re-throwing connection errors from RPCs like the one below. These errors are innocuous errors, usually seen while KDF is restarting during a login. 
Also adds logic to wait for the RPC to be up in native `kdfMain` rather than a static 500ms delay.
```text
I/flutter (22277): Error getting KDF version: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 42740, uri=http://localhost:7783
```
=> fix(native-auth-ops): remove exceptions from logs in KDF restart function

packages/komodo_defi_rpc_methods/lib/src/rpc_methods/withdrawal/withdraw_request.dart, packages/komodo_defi_rpc_methods/lib/src/rpc_methods/withdrawal/withdrawal_rpc_namespace.dart, packages/komodo_defi_sdk/example/lib/screens/withdrawal_page.dart, packages/komodo_defi_types/lib/src/withdrawal/withdrawal_types.dart
- support `ibc_source_channel` when creating withdraw requests
- expose `ibcSourceChannel` on `WithdrawParameters`
- pass the channel from the withdrawal screen example
- `dart format -o none --set-exit-if-changed .`
- `flutter analyze --no-pub` *(fails: 1359 issues found)*
=> feat: add ibc source channel support

packages/komodo_coins/lib/src/config_transform.dart
https://github.com/KomodoPlatform/coins/pull/1368#pullrequestreview-2908037482 has been merged, though logs revealed that app still filtered out BCH. I tracked it back to here.
=> removes BCH from _filteredCoins

packages/komodo_defi_types/lib/src/assets/asset_id.dart, packages/komodo_ui/lib/src/defi/asset/asset_logo.dart
Solves: https://github.com/KomodoPlatform/komodo-wallet/issues/2626
This pull request introduces enhancements to asset handling and display logic in the Komodo codebase. The changes primarily improve the identification and representation of assets, including support for child asset relationships and chain-specific formatting.
* [`packages/komodo_defi_types/lib/src/assets/asset_id.dart`](diffhunk://#diff-99610277540b29ab3e047cabc297437934132d6e71d63d82e4d5c7e43fcfba20L130-R130): Updated the `props` getter in the `AssetId` class to include `chainId.formattedChainId`, ensuring chain-specific formatting is part of equality checks.
* [`packages/komodo_ui/lib/src/defi/asset/asset_logo.dart`](diffhunk://#diff-f4762f83485ef78679336c0337376d787ff2469bc0147b6b3b02d53b677f9e4eL65-R70): Modified the …
=> Fix asset overlay for child assets

packages/komodo_defi_rpc_methods/lib/src/rpc_methods/withdrawal/withdraw_request.dart, packages/komodo_defi_sdk/example/lib/screens/withdrawal_page.dart, packages/komodo_defi_types/lib/src/withdrawal/withdrawal_types.dart
Reverts the temporary IBC channel workaround in #63 by changing the expected type back to `int`
=> fix(withdraw): revert temporary IBC channel type workaround

packages/komodo_coin_updates/lib/src/coins_config/coin_config_repository.dart, packages/komodo_coins/lib/src/startup/startup_coins_provider.dart, packages/komodo_defi_rpc_methods/lib/src/rpc_methods_library.dart, packages/komodo_defi_sdk/lib/src/activation/activation_manager.dart, packages/komodo_defi_sdk/lib/src/assets/asset_lookup.dart, packages/komodo_defi_sdk/lib/src/assets/asset_manager.dart, packages/komodo_defi_sdk/lib/src/assets/custom_asset_history_storage.dart, packages/komodo_defi_sdk/lib/src/transaction_history/strategies/etherscan_transaction_history_strategy.dart
Closes https://github.com/KomodoPlatform/komodo-wallet/issues/3098
- Updates url builder for https://etherscan-proxy-v2.komodo.earth/ to use token contract address (not swap contract address).
- Updates `get_token_info` to ensure mixed case contract address and avoid checksum fail errors
To test:
- Add a custom token for PLG20/BEP20/AVX20/ERC20, and use lowercase contract address.
- Ensure the [correct network](https://github.com/KomodoPlatform/komodo-wallet/issues/3098) is returned. 
- Ensure non-error response (confirmed address conversion to mixed case)
- Enter PLG20/BEP20/AVX20/ERC20 token wallet page with balance and prior transaction activity. History should be populated (There is some work pending in https://github.com/KomodoPlatform/etherscan-mm2-proxy/ so this may not be ready …
=> Fix etherscan urls
